apiVersion: apps/v1
kind: Deployment
metadata:
  name:  es-index
  namespace: ginweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es-index
  template:
    metadata:
      labels:
        app: es-index
    spec:
      containers:
        - name: es-index
          image: 1135189009/es_drop:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
              name: es-index
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 300m
              memory: 500Mi
          volumeMounts:
          - name: varlog
            mountPath: /app/logs/
        - name: fluentd
          image: quay.io/fluentd_elasticsearch/fluentd:v3.4.0
          env:
          - name: FLUENTD_ARGS
            value: -c /etc/fluentd/fluentd.conf
          volumeMounts:
            - name: varlog
              mountPath: /app/logs/
            - name: fluentd-conf
              mountPath: /etc/fluentd/fluentd.conf
              subPath: fluentd.conf
          resources:
            limits:
              memory: 2048Mi
              cpu: 1500m
            requests:
              memory: 100Mi
              cpu: 500m
      volumes:
        - name: varlog
          emptyDir: {}
        - name: fluentd-conf
          configMap:
            name: es-index-fluentd-conf

---
# service
apiVersion: v1
kind: Service
metadata:
  name: es-index
  labels:
    app: es-index
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: es-index